### ISSUE TITLE
Wemos D1 mini pro (ESP8266 based) bare minimal approach failing at 2nd statement

### ISSUE THREAD

**Issue by JackV2020** [shawwwn/uMail#13]
Hello,
Below is the output of my session to my Wemos D1 mini pro which fails at step 2.
I installed Micropython on it using instructions of https://www.jarutex.com/index.php/2020/09/20/119/ and can run Micropython programs. Already built a small web server but can not get umail working. So I flashed the Wemos again and started with a clean install of umail.py only to test the bare minimal approach. So nothing else but the standard boot.py and umail.py on the Wemos.
I changed my username and my password in right values but it does not get very far.

>>> import umail
>>> smtp = umail.SMTP('smtp.gmail.com', 587, username='me@gmail.com', password='*************')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "umail.py", line 30, in __init__
OSError: -2
>>> 

I use umail.py of 29 december 2021 07:52 AM GMT+1 and MicroPython v1.13 of 2020-09-11;

Flashing again and re-downloading umail.py does not help.

**Comment by JackV2020** [comment]
No reaction.
