### ISSUE TITLE
OSError: -202

### ISSUE THREAD

**Issue by NahianMugdho** [shawwwn/uMail#20]
Hello, while I'm trying to run any example, I'm getting the following error-

> Traceback (most recent call last):
>   File "<stdin>", line 2, in <module>
>   File "umail.py", line 30, in __init__
> OSError: -202

my code-
```
import umail
smtp = umail.SMTP('smtp.gmail.com', 587, username='my@gmail.com', password='mypassword')
smtp.to('someones@gmail.com')
smtp.send("This is an example.")
smtp.quit()
```
Please ,help me to solve this. Thanks in advance

**Comment by NahianMugdho** [comment]
The OSError: -202 was solved. I had just entered some new codes to connect to the wifi and the error's gone.
